### ISSUE TITLE
New Item Usage Rules

### ISSUE THREAD

**Issue by edge-blade** [edge-blade/Dota-2-AI-Bot-Experiment#20]
I created the new item builds and mappings in the initial release, but there aren't usage guidelines for all the new ones so sometimes bots may acquire items or upgrades that they won't take advantage of. Early improvement in next release would be to provide some minimum mappings.

**Comment by edge-blade** [comment]
Need the following neutral item definitions:
- [ ] item_unstable_wand (pig pole)
- [ ] item_pogo_stick (tumbler's toy)
- [ ] item_paintball (fae Grenade)
- [ ] item_heavy_blade (witchbane)
- [ ] item_force_field (arcanists armor)

**Comment by edge-blade** [comment]
pig pole -> if running away, use
tumblers toy -> reference blink with greatly reduced range
fae grenade -> If nearby enemy heroes have invis, set target and apply
witchbane -> if ally has debuff, remove it (reference other purge abilities)
arcanists armor -> essentially pass-through on Pipe of Insight for a supercharged spell protection buff)

**Comment by RickyJuno** [comment]
Wraithpact needs default implementation

Possibly look towards Juggernaut healing ward and/or Witch Doctor death ward for wraith pact logic

**Comment by edge-blade** [comment]
I think I might postpone Witchbane until #28 is done. It'll take some time to assemble the list and this shouldn't be a top priority early on in reconstituting the bots. Without it we won't be able to assess if purge should actually take place. For now I'll just make them try to purge themselves if they're silenced or rooted.
